spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

cards:
  message: "Welcome to EazyBank cards related prod APIs "
  contactDetails:
    name: "Aman Sharma- Product Owner"
    email: "amansharma@eazybank.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721